### ISSUE TITLE
Update Config with Whitelist on/off

### ISSUE THREAD

**Issue by MrMirhan** [Aoi39/VelocityWhitelist#1]
When turn on/off whitelist with using command on Velocity it changes status of Config.enableWhitelist but it's not updating on yaml file. If it updates yaml as well, when on reboot the Velocity the latest status will still valid and that would be great.

**Comment by Aoi39** [comment]
This issue will be changed in the next version.

**Comment by MrMirhan** [comment]
Thanks for quick response..

**Comment by Aoi39** [comment]
This problem has been fixed in version 1.0.2.  

[VelocityWhitelist 1.2.0](https://github.com/Aoi39/VelocityWhitelist/releases/tag/1.0.2)
