### ISSUE TITLE
Feature Request: Option to disable chat relay & use whitelist

### ISSUE THREAD

**Issue by LatePacket** [Aoi39/VelocityWhitelist#2]
Not sure if it's currently possible, but would it be possible to have the option to disable the discord chat relay and just use the bot for adding players to the whitelist?

Working great otherwise, Thank you! ^^

**Comment by Aoi39** [comment]
That is a very good idea.
It wasn't a time-consuming change, so I made the change and released it while I was fixing other bugs.
[VelocityDiscordChatBridge-1.0.1](https://modrinth.com/plugin/velocitydiscordchatbridge/version/bQVfzRXO)

**Comment by LatePacket** [comment]
Awesome thank you I will test it in a bit :)

**Comment by LatePacket** [comment]
So to have the bot only work for whitelisting do I just leave the "chatBridgeChannelID" blank? 
Also if that's the case there's no option to also just keep the join leave and proxy startup/shutdown messages?
Having toggles for each separately would be good, but I can work with the above if that's the case for now :)

**Comment by Aoi39** [comment]
To make it work for the whitelist, just empty the ChatBridgeChannel,.
However, we are currently sending join and leave messages to ChatBridgeChannel.
In a future update, it will be possible to set up a dedicated channel for join and leave messages.

**Comment by LatePacket** [comment]
Thanks for the quick reply, it's all working well for the moment cheers!

**Comment by Aoi39** [comment]
Thank you too for choosing my plugin!
